# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BeaconDeploymentTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for BeaconDeploymentTool

  pod 'EstimoteSDK', '~> 4.14.0'
end
